services:
  postgres:
    container_name: API_postgres
    image: postgres:16.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
      PGDATA: /var/lib/postgresql/data/postgres
      PGPORT: 5432
    volumes:
      - ./REST_data:/var/lib/postgresql/data/postgres
    ports:
      - 5433:5432